blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_all, name='blog_all'), 
    path('<int:blog_id>/', views.detail, name='detail'),
]

login_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from login_system import views


urlpatterns = [
    #path('admin/', admin.site.urls),
    #path('login/', views.login, name='login'),#everything blog related go ahead and forward it to the blog app
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.project, name='project'),
    path('blog/', include('blog.urls')),#everything blog related go ahead and forward it to the blog app
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from blog.views import blog_all, detail

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.project, name='project'),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
import datetime

# Create your models here.

class Blog(models.Model):
	title       = models.CharField(max_length=200)
	date        = models.DateField()
	description = models.TextField()

login_system/models.py
#from django.db import models

# Create your models here.

#class Login(models.Model):
#First_name = models.CharField()
#Last_name  = models.CharField(max_length=10)
#	Birthdate  = models.DateField()
#	Email      = models.EmailField()
#	phone      = models.DecimalField(max_value=11, required=False)

portfolio/models.py
from django.db import models

# Create your models here.

#models are like tables in the database and a class is en entity inside the table 
#the class have objects = instances 
#instances have attributtes
class Project(models.Model):
	title       = models.CharField(max_length=100)
	description = models.CharField(max_length=100)
	image       = models.ImageField(upload_to='portfolio/images/')
	url         = models.URLField(blank=True)#if you look at the project in the admin 
#you will find that isn't bold because it's optional unlike description and image

portfolio/forms.py
from django import forms
from .models import Login


class LoginForm(forms.ModelForm):
	class Meta:
		model  = Login
		fields = '__all__'

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog #this is the object
# Create your views here.

def blog_all(request):
	blog_all = Blog.objects.all()#this is Blog model
	return render(request, 'blogss.html', {'blog_all': blog_all})#why I needed to put the variable in the dictionar??


def detail(request, blog_id):
	blog = get_object_or_404(Blog, pk=blog_id)#pk is a database term which refers to the object exits in the datebase
	return render(request, 'detail.html', {'id':blog})

login_system/views.py
from django.shortcuts import render



# Create your views here.

def login(request):
	return render(request, 'login.html')

portfolio/views.py
from django.shortcuts import render
from .models import Project
from blog.views import (blog_all, detail)
# Create your views here.

def project(request):
    projects = Project.objects.all()#this graps all data from database which we created in models.py to display it 
    return render(request, 'project.html', {'projects': projects})

blog/templates/blogss.html
{% extends 'base.html' %}

{% block content %}

<h1>Blog</h1>

{% for Blog in blog_all %}

<a href="URL 'blog_all:detail' blog_id"><h2>{{ Blog.title }}</h2><a/>

<h5>{{ Blog.date }}</h5>

<p>{{ Blog.description|truncatechars:100 }}</p>

{% endfor %}

{% endblock %}

blog/templates/detail.html
{% extends 'base.html' %}

{% block content %}

<h2>{{ Blog.title }}</h2>

<h2>{{ Blog.date|date:'F jS Y' }}</h2>

<h2>{{ Blog.description|safe }}</h2>

{% endblock %}

portfolio/templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <style type="text/css">

      .active {
        background-color: #4CAF50;
      
      }

    </style>
    
    <meta charset="utf-8">

    <title>About Us</title>
          
    <meta name="author" content="Yom">

    <meta name="description" content="This is an example page to demonstrate usage of metadata on web pages.">

    <meta property="og:description" content="This is an example page to demonstrate usage of metadata on web pages.">

    <meta property="og:title" content="Metadata; The HTML &lt;head&gt;, on MDN">

    <link rel="Shortcut Icon" href="now.jpg" type="image/x-icon">

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>

    <link href="{% static 'fontawesome_free/css/all.min.css' %}" rel="stylesheet" type="text/css">

    <link href="{% static 'fontawesome_pro/css/fontawesome.css' %}" rel="stylesheet" type="text/css">

    <link href="{% static 'fontawesome_pro/css/brands.css' %}" rel="stylesheet" type="text/css">

    <link href="{% static 'fontawesome_pro/css/solid.css' %}" rel="stylesheet" type="text/css">

    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>

    <!--<script rel="script" src="{% static 'script.js' %}"defer></script>

    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>--->

<body>
  <header>
    <div class="list">
      <ul>
        <li><a id="home" href="http://127.0.0.1:8000/" id="home">Home</a>
          <li><a id="blog" href="http://127.0.0.1:8000/blog/" id="blog"> Blog</a>
            <li><a id="about" href="" id="about">About</a>
              <li>
                <form method="GET" action="http://127.0.0.1:8000/blog/">
                <input id="s" type="text" name="search" placeholder="search">
                </button>
                <div class="dropdown">
                  <button class="dropbtn">Make Your account</button>
                  <div class="dropdown-content">
                    <a href="#">Login</a>
                    <a href="#">Sign In</a>
                    <a href="#">Sign Up</a>
                  </div>
                </div>
              </ul>
            </div>
          </header>


<!---we could have multiple headers so it's best to give it an idea-->
<header class="main_header">
    <h1 style="color: black;
    text-align: center;">
    Egyptian psychedelic community</h1>
  </header>

<!--here we made a form--->
              <div class="form">
              <form action="" method="POST">
                <label>First Name</label>
                <input type="text" name="first-name" placeholder="Enter your first name"><!--div is used to create another line--->
                <br>

                <label>Last Name</label>
                <input type="text" name="Lastname" placeholder="Enter your last name">
                <br>
                <br>
                <input class="button" type="submit" name="submit">
                <button class="button">Login</button>
              </form>

              <!----We can also create buttons outside the form with the button tag--->
              
            </div>
            <div>

            <!---tags are meant to communicate meaning and make structural content-->
            <img class="img" 
             src="{% static 'images/now.jpg' %}" alt="Photo" width="600" align="right">
           </div>


          <section>
            <article class="art">
            <!---h1>The Crushing Bore</h1-->

            <!---p class="chris"--->
          <!--By Chris Mills</p>-->

            <h2>Chapter 1: The dark night</h2>

            <p>
            It was a <i>dark night</i>. Somewhere, an owl hooted. The rain lashed down on the ...
            In my younger and more vulnerable years my father gave me some advice that I've been turning over in my mind ever <i>since</i>. 'Whenever you feel like criticizing anyone,' he told me, 'just remember that all the people in this world haven't had the advantages that you've had.</p>


            <h2>Chapter 2: The eternal silence</h2>

            <p>
            Our protagonist could not so much as a whisper out of the shadowy figure
            In my younger and <div class="dropdown">more vulnerable</div> years my father gave me some advice that I've been turning over in my mind ever since. 'Whenever you feel like criticizing anyone,' he told me, 'just remember that all the people in this world haven't had the advantages that you've had.</p>

            <h3>The specter speaks</h3>

            <p>
            Several more hours had passed, when all of a sudden the specter sat bolt upright and exclaimed, "Please have mercy on my soul!In my younger and more vulnerable years my father gave me some advice that I've been turning over in my mind ever since</p>
          </article>

        </section>
</body>
<!---same for the footer we can have multiple footers-->
  <footer id="main_footer">

    <table>

      <tr>

        <td>Contact us at</td>

        <td><a id="yomna" href="">Yomnaali1718@gmail.com</a></td>

      </tr>

    </table>

  </footer>

  </html>

portfolio/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <link rel="shortcut icon" type="image/jpg" href="logo.jpg"/>
    <!-- Required meta tags -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">



    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">


    <title>LSD</title>
  </head>
  <body>
    <style type="text/css">
   body { background:  !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
    </style>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">lsd</a>
    
    <img src="media/portfolio/images/logo.jpg" width="35" height="30" alt="">
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="" href="project.html">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="">About</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="search">Search</button>
      </form>
    </div>
  </div>
</nav>
<center>

{% block content %}{% endblock %}


    <!-- Optional JavaScript; choose one of the two! -->
  

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
   </center>
  </body>
</html>

portfolio/templates/home.html
{% extends 'project.html' %}

{% block content %}

{% endfor %}

portfolio/templates/javascript.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

</body>
</html>

portfolio/templates/login.html
<!DOCTYPE html>
<html lang="en-US">
<head>
	<title>Account</title>
</head>
<body>
	<form action = "" method = "POST"> 
	{% csrf_token %} 
	{{ form.as_p }} 
	<input type="submit" value="Submit"> 
</form> 

</body>
</html>

portfolio/templates/project.html
{% extends 'base.html' %}

{% block content %}

{% load static %}


<link type="icon" href="{% static 'images/logo.png' type='image/png' %}">

<h1>My Acid </h1>



<p><a href="{% url 'blog:blog_all' %}">Blog</a></p>
<br>


<img src="{% static 'photo/now.jpg' %}">

{% for project in projects %}


<h2>{{ project.title }}</h2>
<p>{{ project.description }}</p>
<img src="{{ project.image.url }}">
{% if project.url %}
<br><a href="{{ project.url }}">Link</a>
{% endif %}

{% endfor %}

{% endblock %}